#!/usr/bin/env bash
# issue-4 Phase 1 — CLI read/write/feedback path (docs/issues/issue-4).
#
# Proves the three new commands close the loop WITHOUT an HTTP server, which is the whole point:
# under skill-style deployment the agent only has bash.
#   (A) remember writes an atomic note that recall finds immediately (FTS trigger fired)
#   (B) re-running remember with identical text is idempotent — one session, and crucially
#       ONE recall_fts row per ref (a rewrite would leave a duplicate and double the hits)
#   (C) provenance is recorded as source_type='cli_note'
#   (D) feedback writes explicit utility back into memory_utility, kept apart from the reuse proxy
#   (E) an unknown recall_id is a graceful no-op, not an error

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
export MEMORIA_HOME="$TMP_DIR/home"
DB="$MEMORIA_HOME/.memory/sessions.db"
BSQ="$ROOT_DIR/node_modules/better-sqlite3"
CLI="$ROOT_DIR/cli"

cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

# Query the DB with a one-liner; $1 = SQL returning a single scalar column.
q() {
    node -e "
      const D=require('$BSQ');
      const db=new D('$DB',{readonly:true});
      const r=db.prepare(process.argv[1]).get();
      console.log(r ? Object.values(r)[0] : '');
    " "$1"
}
jq_field() { node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{const j=JSON.parse(d);console.log(eval("j"+process.argv[1]))})' "$1"; }

echo "[cli-memory] init"
"$CLI" init >/dev/null

echo "[cli-memory] (A) remember writes a note that recall finds"
"$CLI" remember "改用 pnpm 作為套件管理器" --project demo --rationale "lockfile 是權威" >/dev/null
"$CLI" remember "recall 排序改用 relevance 顯示" --type skill --project demo --category cli >/dev/null

HITS=$("$CLI" recall "pnpm 套件管理器" --project demo --json | jq_field '.data.length')
[ "$HITS" -ge 1 ] || { echo "  ✗ recall found nothing right after remember"; exit 1; }
echo "  recall hits: $HITS"

SKILL_HITS=$("$CLI" recall "relevance 顯示" --project demo --json | jq_field '.data.length')
[ "$SKILL_HITS" -ge 1 ] || { echo "  ✗ skill note not recallable"; exit 1; }

echo "[cli-memory] (B) identical remember is idempotent (session count AND fts rows)"
SESSIONS_BEFORE=$(q "SELECT COUNT(*) c FROM sessions")
"$CLI" remember "改用 pnpm 作為套件管理器" --project demo --rationale "lockfile 是權威" >/dev/null
SESSIONS_AFTER=$(q "SELECT COUNT(*) c FROM sessions")
[ "$SESSIONS_BEFORE" = "$SESSIONS_AFTER" ] || {
    echo "  ✗ session count changed on re-run: $SESSIONS_BEFORE -> $SESSIONS_AFTER"; exit 1; }

DUPES=$(q "SELECT COUNT(*) c FROM (SELECT kind, ref_id FROM recall_fts GROUP BY kind, ref_id HAVING COUNT(*) > 1)")
[ "$DUPES" = "0" ] || { echo "  ✗ duplicate recall_fts rows after re-run: $DUPES"; exit 1; }

HITS_AFTER=$("$CLI" recall "pnpm 套件管理器" --project demo --json | jq_field '.data.length')
[ "$HITS" = "$HITS_AFTER" ] || { echo "  ✗ hit count changed after idempotent re-run: $HITS -> $HITS_AFTER"; exit 1; }
echo "  sessions=$SESSIONS_AFTER, no duplicate fts rows, hits stable"

echo "[cli-memory] (C) provenance recorded as cli_note"
PROV=$(q "SELECT COUNT(*) c FROM memory_sources WHERE source_type='cli_note'")
[ "$PROV" -ge 2 ] || { echo "  ✗ expected >=2 cli_note provenance rows, got $PROV"; exit 1; }
echo "  provenance rows: $PROV"

echo "[cli-memory] (D) feedback writes explicit utility back"
RID=$("$CLI" recall "pnpm 套件管理器" --project demo --json | jq_field '.meta.recall_id')
[ -n "$RID" ] || { echo "  ✗ recall did not return a recall_id"; exit 1; }
HIT_IDS=$("$CLI" recall "pnpm 套件管理器" --project demo --json | jq_field '.data.map(h=>h.id).join(",")')
"$CLI" feedback "$RID" --signal explicit --score 0.9 --hits "$HIT_IDS" >/dev/null

EXPLICIT=$(q "SELECT COUNT(*) c FROM memory_utility WHERE explicit_observations > 0")
[ "$EXPLICIT" -ge 1 ] || { echo "  ✗ no explicit observation recorded"; exit 1; }
# RFC §2.4: explicit and reuse accumulate separately and are never summed.
REUSE_LEAK=$(q "SELECT COUNT(*) c FROM memory_utility WHERE explicit_observations > 0 AND observations > 0")
[ "$REUSE_LEAK" = "0" ] || { echo "  ✗ explicit signal leaked into the reuse accumulator"; exit 1; }
echo "  explicit rows: $EXPLICIT (reuse accumulator untouched)"

echo "[cli-memory] (E) unknown recall_id is a graceful no-op"
"$CLI" feedback rt_does_not_exist --score 0.5 >/dev/null || {
    echo "  ✗ unknown recall_id should exit 0"; exit 1; }
UPDATED=$("$CLI" feedback rt_does_not_exist --score 0.5 --json | jq_field '.data.updated')
[ "$UPDATED" = "false" ] || { echo "  ✗ expected updated=false, got '$UPDATED'"; exit 1; }

echo "[cli-memory] (F) brief compiles a derived markdown view"
BRIEF="$MEMORIA_HOME/knowledge/BRIEF.md"
"$CLI" brief --project demo >/dev/null
[ -f "$BRIEF" ] || { echo "  ✗ BRIEF.md not written"; exit 1; }
grep -q "generated by: memoria brief" "$BRIEF" || { echo "  ✗ missing generated header"; exit 1; }
grep -q "do not edit by hand" "$BRIEF" || { echo "  ✗ missing do-not-edit marker"; exit 1; }
grep -q "改用 pnpm 作為套件管理器" "$BRIEF" || { echo "  ✗ recent decision missing from brief"; exit 1; }
# (D) attributed explicit utility, so the UFL section must carry it — and as readable text,
# not the raw JSON blob the event stores.
grep -q "explicit ×" "$BRIEF" || { echo "  ✗ high-utility section did not pick up the explicit outcome"; exit 1; }
grep -q '"decision":' "$BRIEF" && { echo "  ✗ raw event JSON leaked into the brief"; exit 1; }
# A note owns two refs (session + event) and an outcome attributes utility to both — they must
# collapse to one line, or every CLI note is listed twice in the brief.
NOTE_LINES=$(grep -c "改用 pnpm 作為套件管理器" "$BRIEF" || true)
[ "$NOTE_LINES" = "2" ] || { echo "  ✗ expected the note once under decisions and once under high-utility, got $NOTE_LINES lines"; exit 1; }
echo "  brief written with decisions + UFL section"

echo "[cli-memory] (G) brief is stable across runs (timestamp aside)"
cp "$BRIEF" "$TMP_DIR/brief-1.md"
"$CLI" brief --project demo >/dev/null
diff <(grep -v "generated by" "$TMP_DIR/brief-1.md") <(grep -v "generated by" "$BRIEF") >/dev/null || {
    echo "  ✗ brief content changed between identical runs"; exit 1; }

# --stdout must not touch the file.
"$CLI" brief --project demo --stdout | grep -q "# Memoria Brief" || { echo "  ✗ --stdout produced no markdown"; exit 1; }
echo "  stable, and --stdout does not write"

echo "[cli-memory] (H) stats reports observed utility per route"
# Additive discipline first: with no outcomes recorded, the block must be absent entirely.
FRESH="$TMP_DIR/home-fresh"
MEMORIA_HOME="$FRESH" "$CLI" init >/dev/null
MEMORIA_HOME="$FRESH" "$CLI" remember "改用 pnpm 作為套件管理器" --project demo >/dev/null
ABSENT=$(MEMORIA_HOME="$FRESH" "$CLI" stats --json | jq_field '.data.recallRouting?.routeUtility === undefined')
[ "$ABSENT" = "true" ] || { echo "  ✗ routeUtility must be absent until an outcome exists"; exit 1; }

# Two routes, deliberately different utility, so the comparison has something to say.
report_on() { # $1 = mode, $2 = utility score
    local rid hits
    rid=$(MEMORIA_HOME="$FRESH" "$CLI" recall "pnpm 套件管理器" --project demo --mode "$1" --json | jq_field '.meta.recall_id')
    [ -n "$rid" ] && [ "$rid" != "undefined" ] || { echo "  ✗ recall on route $1 issued no recall_id"; exit 1; }
    hits=$(MEMORIA_HOME="$FRESH" "$CLI" recall "pnpm 套件管理器" --project demo --mode "$1" --json | jq_field '.data.map(h=>h.id).join(",")')
    MEMORIA_HOME="$FRESH" "$CLI" feedback "$rid" --score "$2" --hits "$hits" >/dev/null
}
report_on keyword 0.4
report_on keyword 0.6
report_on tree 0.9
report_on tree 0.8

MEMORIA_HOME="$FRESH" "$CLI" stats --json | node -e '
const ru = JSON.parse(require("fs").readFileSync(0, "utf8")).data.recallRouting.routeUtility;
const fail = (m) => { console.error("  ✗ " + m + ": " + JSON.stringify(ru)); process.exit(1); };
if (ru.scoredQueries !== 4) fail("expected 4 scored queries");
if (ru.routes.length !== 2) fail("expected 2 routes");
if (ru.routes[0].route_mode !== "tree") fail("routes must be sorted best-first");
if (ru.best !== "tree") fail("best route should be tree (0.85 vs 0.5)");
if (Math.abs(ru.uplift - 0.35) > 1e-6) fail("uplift should be 0.35");
'
MEMORIA_HOME="$FRESH" "$CLI" stats | grep -q "route_utility:" || { echo "  ✗ human-readable stats missing route_utility line"; exit 1; }
echo "  absent with no outcomes; after 2 routes: best=tree uplift=0.35"

echo "[cli-memory] ✓ all checks passed"
